version: "3.3"
services:
  todo-backend:
    image: todo-backend
    build: .
    ports:
      - 8000:8000
    links:
      - mongo
    volumes:
      - .:/home/app/backend
    depends_on:
      - mongo
    restart: always
  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - "db-mongo:/data/db"
  mongoui:
    image: mongo-express
    depends_on:
      - mongo
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongo
    restart: always

volumes:
  db-mongo:
    driver: local
