// account
export const USER_LOGIN = "USER_LOGIN";
export const USER_LOGOUT = "USER_LOGOUT";
export const FETCH_TODO_DETAILS = "FETCH_TODO_DETAILS";
export const SAVE_FETCHED_TODO_DETAILS = "SAVE_FETCHED_TODO_DETAILS";
export const FETCH_TODO_DETAILS_ERROR = "FETCH_TODO_DETAILS_ERROR";
export const REQUEST_TODO_LIST = "REQUEST_TODO_LIST";
export const SAVE_TODO_LIST = "SAVE_TODO_LIST";
export const ERROR_TODO_LIST = "ERROR_TODO_LIST";

export const NOT_API_CALL = "NOT_API_CALL";
