// account
export const USER_LOGIN = "USER_LOGIN";
export const USER_LOGOUT = "USER_LOGOUT";
export const USER_SIGNUP = "USER_SIGNUP";
export const FETCH_USER_DETAILS = "FETCH_USER_DETAILS";
export const SAVE_USER_DETAILS = "SAVE_USER_DETAILS";

export const REQUEST_ADD_TODO = "REQUEST_ADD_TODO";
export const REQUEST_UPDATE_TODO = "REQUEST_UPDATE_TODO";
export const REQUEST_DELETE_TODO = "REQUEST_DELETE_TODO";
export const FETCH_TODO_DETAILS = "FETCH_TODO_DETAILS";
export const SAVE_FETCHED_TODO_DETAILS = "SAVE_FETCHED_TODO_DETAILS";
export const FETCH_TODO_DETAILS_ERROR = "FETCH_TODO_DETAILS_ERROR";
export const REQUEST_TODO_LIST = "REQUEST_TODO_LIST";
export const SAVE_TODO_LIST = "SAVE_TODO_LIST";
export const ERROR_TODO_LIST = "ERROR_TODO_LIST";

export const NOT_API_CALL = "NOT_API_CALL";
export const REDIRECT_REQUEST = "REDIRECT_REQUEST";
export const CLEAR_REDIRECT_REQUEST = "CLEAR_REDIRECT_REQUEST";
